collector/urls.py
from django.conf.urls import url
# from django.urls import path
from . import views

app_name = 'collector'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^requests/$', views.RequestListView.as_view(), name='requests_list'),
    url(r'^request_detail/$', views.RequestDetailView.as_view(), name='request_detail'),
    url(r'^receivers/$', views.ReceiverListView.as_view(), name='receivers_list'),
    url(r'^receiver/create/$', views.receiver_create, name='add_receiver'),
    url(r'^receiver/detail/(?P<pk>\d+)$', views.receiver_detail, name='receiver_detail'),
    url(r'^receiver/edit/(?P<pk>\d+)$', views.receiver_edit, name='edit_receiver'),
    url(r'^receiver/delete/$', views.receiver_delete, name='delete_receiver'),

]

recycle/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^collector/', include('collector.urls')),
]

collector/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
from django.urls import reverse


class Receiver(models.Model):

    fullname = models.CharField(max_length=40, verbose_name='نام کامل')
    mobile_number = models.CharField(max_length=40, verbose_name='شماره همراه')
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                verbose_name='مدیر',related_name='receivers', default=User.username)

    def get_absolute_url(self):
        return reverse('collector:receiver_detail', args=[str(self.id)])


class MobileUser(models.Model):

    mobile_number = models.CharField(max_length=40, verbose_name='شماره همراه')
    fullname = models.CharField(max_length=40, verbose_name='نام کامل')
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='mobile_user')


class RecyclingRequest(models.Model):

    requester = models.ForeignKey('MobileUser', on_delete=models.SET_NULL, null=True,
                                  verbose_name='درخواست دهنده', related_name='user_requests')
    receiver = models.ForeignKey('Receiver', on_delete=models.SET_NULL, null=True,
                                 verbose_name='دریافت کننده', related_name='receiver_requests')
    address = models.TextField(blank=False, verbose_name='آدرس')

    RECYCLE_STATUS = (
        ('ثبت اطلاعات', 'ثبت اطلاعات'),
        ('تعیین پذیرنده', 'تعیین پذیرنده'),
        ('حذف درخواست', 'حذف درخواست'),
    )

    status = models.CharField(max_length=40, choices=RECYCLE_STATUS, blank=True,
                              default='ثبت اطلاعات', verbose_name='وضعیت')

    TRASH_TYPE = (
        ('خشک', 'خشک'),
        ('تر', 'تر'),
        ('کاغذ', 'کاغذ'),
        ('فلز', 'فلز'),
    )
    trash_type = models.CharField(max_length=40, choices=TRASH_TYPE,
                                  default='خشک', verbose_name='نوع زباله')

collector/forms.py
from django import forms
from django.forms import ModelForm, modelformset_factory
from . import models


# class ReceiverForm(forms.Form):
#     fullname = forms.CharField(label='fullname', max_length=40)
#     mobile_number = forms.CharField(label='mobile_number', max_length=40)

class ReceiverClassForm(ModelForm):
    class Meta:
        model = models.Receiver
        fields = ['fullname', 'mobile_number', 'manager']


class RecyclingRequestClassForm(ModelForm):
    class Meta:
        model = models.RecyclingRequest
        fields = ['requester', 'receiver', 'address', 'status', 'trash_type']


RecyclingRequestModelFormset = modelformset_factory(
    models.RecyclingRequest,
    fields=('requester', 'receiver', 'address', 'status', 'trash_type' ),
    extra=1,
    # widgets={'name': forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'placeholder': 'Enter Book Name here'
    #     })
    # }
)

collector/views.py
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.views import generic

from . import models, forms


def index(request):
    # if request.method == 'POST':
    #     form = forms.ReceiverClassForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect('/collector/receivers/')

    RecyclingRequestFormSet = formset_factory(forms.RecyclingRequestClassForm)
    if request.method == 'POST':
        request_formset = RecyclingRequestFormSet(request.POST)
        if request_formset.is_valid():
            for form in request_formset:
                id = form.id
                status = form.status
                # models.RecyclingRequest.objects.filter(id=id).update(status=status)
                form.save()

    # else:
    #     number = models.RecyclingRequest.objects.filter(status="ثبت اطلاعات")
    #     return render(
    #         request,
    #         'index.html',
    #         context={'recycle_request': number},
    #     )

    else:
        request_formset = RecyclingRequestFormSet()
        items = models.RecyclingRequest.objects.filter(status="ثبت اطلاعات")
        request_formset = forms.RecyclingRequestModelFormset(
            queryset=models.RecyclingRequest.objects.filter(status="ثبت اطلاعات"))
        # for item in items:
        #     print(item)
        #     forms.RecyclingRequestClassForm(
        #         initial={'id': item.id, 'requester': item.requester.fullname, 'receiver': item.receiver.fullname,
        #                  'address': item.address, 'status': item.status, 'trash_type': item.trash_type})

    return render(request, 'index.html', {'formset': request_formset})


class RequestListView(generic.ListView):
    model = models.RecyclingRequest
    context_object_name = 'recycle_request'
    template_name = 'request_list.html'


class RequestDetailView(generic.ListView):
    model = models.RecyclingRequest
    context_object_name = 'recycle_request'
    template_name = 'request_detail.html'


class ReceiverListView(generic.ListView):
    model = models.Receiver
    context_object_name = 'receiver_list'
    template_name = 'receiver_list_table.html'


class ReceiverCreate(generic.CreateView):
    model = models.Receiver
    fields = {"fullname", "mobile_number"}
    # initial =
    template_name = 'receiver_create.html'


def receiver_create(request):
    if request.method == 'POST':
        form = forms.ReceiverClassForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/collector/receivers/')

    else:
        form = forms.ReceiverClassForm()

    return render(request, 'receiver_create.html', {'form': form})


def receiver_detail(request, id):
    receiver = models.Receiver.objects.filter(id=id)
    context_object_name = receiver
    return render(
        request,
        'receiver_detail.html',
        context={'receiver': receiver},
    )


def receiver_edit(request, id):
    if request.method == 'POST':
        receiver = models.Receiver.objects.filter(id=id).update(request)
        request_formset = forms.RecyclingRequestModelFormset(
            queryset=models.RecyclingRequest.objects.filter(status="ثبت اطلاعات"))

        return render(request, 'index.html', {'formset': request_formset})


def receiver_delete(request, id):
    if request.method == 'POST':
        receiver = models.Receiver.objects.filter(id=id).delete()
        context_object_name = receiver
        return render(
            request,
            'receiver_detail.html',
            context={},
        )
    else:
        pass

collector/templates/base.html
{% load static %}

<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}داشبورد{% endblock %}</title>

    <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/css/plugins/bootstrap-rtl/bootstrap-rtl.min.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <!-- <link href="{% static 'dashboard/css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet"> -->
    <link href="{% static 'dashboard/css/plugins/persian-datepicker/persian-datepicker.css' %}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{% static 'dashboard/css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

    <!-- Gritter -->
    <link href="{% static 'dashboard/js/plugins/gritter/jquery.gritter.css' %}" rel="stylesheet">

    <!-- c3 Charts -->
    <link href="{% static 'dashboard/css/plugins/c3/c3.min.css' %}" rel="stylesheet">

    <link href="{% static 'dashboard/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">

    <!-- Data Tables -->
    <link href="{% static 'dashboard/css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">

    <!-- iCheck -->
    <link href="{% static 'dashboard/css/plugins/iCheck/custom.css' %}" rel="stylesheet">

    <!-- Input Mask-->
    <link href="{% static 'dashboard/css/plugins/jasny/jasny-bootstrap.min.css' %}">
</head>

<body class="rtls">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span>
                                        <i class="fa fa-user-circle-o fa-5x"></i>
                                    </span>
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">کاربر : {{ user.get_full_name|default:user.username }}</strong>
                                    </span>

                                </span>
                            </a>
                        </div>
                        <div class="logo-element">منو</div>
                    </li>
                    {% block menu %}
                    <li class="active">
                        <a href="{% url 'collector:requests_list' %}"><i class="fa fa-globe"></i> <span class="nav-label">داشبورد</span>&nbsp;<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li class="active"><a href="{% url 'collector:index' %}">داشبورد</a></li>
                            <li class="active"><a href="{% url 'collector:requests_list' %}">همه درخواست ها</a></li>
                            <li><a href="{% url 'collector:request_detail' %}">جزئیات درخواست</a></li>
                        </ul>
                    </li>

                    <li class="active">
                        <a href="{% url 'collector:receivers_list' %}"><i class="fa fa-user-circle"></i> <span class="nav-label"> مدیریت پذیرنده ها </span></a>
                    <ul class="nav nav-second-level">
                                <li class="active"><a href="{% url 'collector:receivers_list' %}">همه پذیرنده ها</a></li>
                                <li><a href="{% url 'collector:add_receiver' %}">ایجاد پذیرنده ها</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/dashboard/mailbox/"><i class="fa fa-envelope"></i><span class="nav-label"> صندوق پیام </span>&nbsp;<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="/dashboard/mailbox/inbox">پیام های دریافتی</a></li>
                            <li><a href="/dashboard/mailbox/sent">پیام های ارسالی</a></li>
                            <li><a href="/dashboard/mailbox/trash">پیام های حذف شده</a></li>
                            <li><a href="/dashboard/mailbox/compose">ارسال پیام</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/dashboard/report/"><i class="fa fa-area-chart"></i><span class="nav-label"> گزارشات </span>&nbsp;<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="/dashboard/report/agreements">قرارداد ها</a></li>
                            <li><a href="/dashboard/report/leakages"> نشت ها</a></li>
                        </ul>
                    </li>
                    {% endblock %}
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="جست و جو..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">خوش آمدید</span>
                </li>

                <li>
                    <a href="/accounts/logout/">
                        <i class="fa fa-sign-out"></i> خروج
                    </a>
                </li>
            </ul>

        </nav>
        </div>

        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>مسیر</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="/dashboard">خانه</a>
                    </li>
                    {% block breadcrumb %}
                    <li>
                        <a>بخش</a>
                    </li>
                    <li class="active">
                        <strong>زیربخش</strong>
                    </li>
                    {% endblock %}
                </ol>
            </div>
            <div class="col-lg-2">

            </div>
        </div>
        <!--<div class="row  border-bottom white-bg dashboard-header">-->
            <!--<div class="col-md-3">-->
                <!--<h2>داشبورد مدیریت</h2>-->
            <!--</div>-->
        <!--</div>-->

        <div class="row">
            <div class="col-lg-12">
                <div class="wrapper wrapper-content">
                        <div class="row">
                        {% block content %}
                            <div class="col-md-12">
                            </div>
                        {% endblock %}
                        </div>
                </div>
                <div class="footer">
                    <div class="pull-right">
                        <strong>Copyright</strong> Gereh Co. &copy; 2018
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'dashboard/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'dashboard/js/inspinia.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/pace/pace.min.js' %}"></script>

    <!-- Date picker -->
    <script src="{% static 'dashboard/js/plugins/persian-datepicker/persian-datepicker.js' %}"></script>

    <!-- d3 and c3 charts -->
    <script src="{% static 'dashboard/js/plugins/d3/d3.min.js' %}"></script>
    <script src="{% static 'dashboard/js/plugins/c3/c3.min.js' %}"></script>

    <!-- Data Tables -->
    <script src="{% static 'dashboard/js/plugins/dataTables/datatables.min.js' %}"></script>

    <!-- iCheck -->
    <script src="{% static 'dashboard/js/plugins/iCheck/icheck.min.js' %}"></script>

    <!-- Input Mask-->
    <script src="{% static 'dashboard/js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>

    <script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>

    {% block script %}<script></script>{% endblock %}
</body>
</html>

collector/templates/form_create_receiver.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Basic Form</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <link href="css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

</head>

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>All form elements <small>With custom checbox and radion elements.</small></h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>

                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="get" class="form-horizontal">
                                <div class="form-group"><label class="col-sm-2 control-label">FullName</label>

                                    <div class="col-sm-10"><input type="text" class="form-control"></div>
                                </div>
                                <div class="form-group"><label class="col-sm-2 control-label">Mobile</label>

                                    <div class="col-sm-10"><input type="text" class="form-control"></div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <button class="btn btn-white" type="submit">cancel</button>
                                        <button class="btn btn-primary" type="submit">Save changes</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    <!-- Mainly scripts -->
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>
    <script src="js/plugins/pace/pace.min.js"></script>

    <!-- iCheck -->
    <script src="js/plugins/iCheck/icheck.min.js"></script>
        <script>
            $(document).ready(function () {
                $('.i-checks').iCheck({
                    checkboxClass: 'icheckbox_square-green',
                    radioClass: 'iradio_square-green',
                });
            });
        </script>
</body>

</html>

collector/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <form method="post" action="">
        {{ formset.management_form }}
        <div>

            {% for form in formset %}
                {{form}}
            {% endfor %}
        </div>
        <input class="btn btn-primary" href="/collector/receiver/{{ receiver.id }}/edit/" type="submit" value="save"/>
    </form>

   <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>FooTable with row toggler, sorting and pagination</h5>

                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">

                            <table class="footable table table-stripped toggle-arrow-tiny">
                                <thead>

                                <tr>

                                    <th data-toggle="true">RequestID</th>
                                    <th>Requester</th>
                                    <th>Receiver</th>
                                    <th>Status</th>
                                    <th>TrashType</th>
                                    <th data-hide="all">Address</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% if recycle_request %}
                                    {% for request in recycle_request %}
                                    <tr>
                                        <td>{{ request.id}}</td>
                                        <td>{{ request.requester.fullname}}</td>
                                        <td>{{ request.receiver.fullname}}</td>
                                        <td>{{ request.status}}</td>
                                        <td>{{ request.trash_type}}</td>
                                        <td>{{ request.address}}</td>

                                    {% endfor %}

                                {% endif %}
                                </tr>
                                </tbody>

                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

        </div>

{% endblock %}

collector/templates/receiver_create.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>All form elements <small>With custom checbox and radion elements.</small></h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>

                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="post" class="form-horizontal">
                                {% csrf_token %}
                                   {{ form }}
                                <input class="btn btn-primary" type="submit" value="save"/>
                                <a class="btn btn-primary" href="/collector/receivers/">cancel</a>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

collector/templates/receiver_detail.html
{% extends "collector/base.html" %}

{% block content %}


    <hr>

       <form action="" method="post">

        {% csrf_token %}
        <table>
        {{ form }}
        </table>
           <a class="btn btn-primary" href="/collector/receiver/{{ receiver.id }}/edit/">Edit</a>
           <a class="btn btn-primary" href="/collector/receiver/{{ receiver.id }}/delete/">Delete</a>
    </form>



{% endblock %}

collector/templates/receiver_list_table.html
{% extends "base.html" %}

{% load static %}

{% block content %}

   <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>FooTable with row toggler, sorting and pagination</h5>

                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">

                            <table class="footable table table-stripped toggle-arrow-tiny">
                                <thead>

                                <tr>

                                    <th data-toggle="true">ID</th>
                                    <th>FULLNAME</th>
                                    <th>Phone</th>
                                    <th data-hide="all">MANAGER</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% if receiver_list %}
                                    {{ receiver.full_name}}
                                    {% for receiver in receiver_list %}
                                    <tr>
                                        <td><a href="{{ receiver.get_absolute_url }}">{{ receiver.id}}</a></td>
                                        <td>{{ receiver.fullname}}</td>
                                        <td>{{ receiver.mobile_number}}</td>
                                        <td>{{ receiver.manager.username}}</td>

                                    {% endfor %}

                                {% endif %}

                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

        </div>


{% endblock %}